version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./src:/app/src
    depends_on:
      - whisper
    environment:
      - WHISPER_SERVER_URL=http://whisper:8000/v1/
    networks:
      - app-network

  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: faster-whisper-server
    ports:
      - "8000:8000"
    volumes:
      - ./models/whisper-data:/root/.cache/huggingface
    environment:
      - OPENAI_API_KEY=cant-be-empty # Placeholder, isn't needed for Lucy
      - OPENAI_BASE_URL=http://localhost:8000/v1/
      - UV_HTTP_MAX_REQUEST_SIZE=52428800 # 50 MB in bytes, increase if you need to upload larger files.
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
